### PR TITLE
Update for Crystal 1.0.0; bump version to 0.3.4

### PR DESCRIPTION
**Pull request by dbohdan**

### CODE REVIEW

**Comment by RX14** [comment]
I assume the specs pass

otherwise LGTM

**Comment by dbohdan** [comment]
They pass for me locally and [on Travis CI](https://travis-ci.com/github/dbohdan/fast_irc.cr/builds/221345467).

```
> crystal spec
...................................

Finished in 57.12 milliseconds
35 examples, 0 failures, 0 errors, 0 pending

> crystal version
Crystal 1.0.0 [dd40a2442] (2021-03-22)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by RX14** [comment]
Wonderful!

**Comment by dbohdan** [comment]
Thanks for responding so quickly!  Please add a new tag, too.

**Comment by RX14** [comment]
All done!

**Comment by dbohdan** [comment]
Thanks again.

**Pull request merged**
